In [5]:
import numpy as np
import pandas as pd

In [2]:
data = {'A':[1,2,3,4],'B':[4,5,6,7],'C':[2,3,4,6]}
data_frame = pd.DataFrame(data)
print(data_frame)

   A  B  C
0  1  4  2
1  2  5  3
2  3  6  4
3  4  7  6


In [3]:
select = data_frame.sample(2,axis=1)
print(select)

   A  B
0  1  4
1  2  5
2  3  6
3  4  7


In [4]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
x = [[1,1],[2,2],[2,1],[1,2]]
y = [1,1,1,0]
knn.fit(x,y)
print(knn.predict([[1,2]]))

[1]


In [5]:
data = np.array([[1,2,3],[2,1,2],[2,3,1],[3,2,1]])
data_ = data.T
for i in data_:
    unique, counts = np.unique(i, return_counts=True)
    most_number = unique[np.argmax(counts)]
    print(most_number)

2
2
1


In [6]:
data = pd.DataFrame({'A':[1,2,3,4],'B':[2,3,4,5]})
print(data)

   A  B
0  1  2
1  2  3
2  3  4
3  4  5


In [9]:
data['C'] = np.array([3,4,5,6])

In [10]:
print(data)

   A  B  C
0  1  2  3
1  2  3  4
2  3  4  5
3  4  5  6


In [ ]:
a = []
print(np.random.choice())

In [15]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [26]:
class A():
    def __init__(self,a):
        self.a = a
    def aa(self,b):
        self.b = b
a = A(1)
a.aa(2)
print(a.__dict__)

AttributeError: 'A' object has no attribute 'b'

In [4]:
import numpy as np

# 假设你的 NumPy 数组是
arr = np.array([0,0,1,1,1,1,1,2,3,3,3,3,0])

# 使用 np.unique 来计算每个元素的频次
unique_elements= np.unique(arr, return_counts=False)
# print(counts)
print(unique_elements)
# 计算总元素个数
total_count = len(arr)

# 计算每个元素的比例
# proportions = counts / total_count

# 打印结果
# for element, proportion in zip(unique_elements, proportions):
#     print(f"元素 {element} 的比例是 {proportion:.2f}")

[0 1 2 3]


In [29]:
data = np.array([[1,2,3],[4,5,6],[1,2,3]])
data[0][0]

1

In [9]:
data = {
    'A': [1, 2, 3, 4],
    'B': [10, 20, 30, 40],
    'C': [100, 200, 300, 400]
}

df = pd.DataFrame(data)

# print("原始DataFrame:")
# print(df)
# print(df.min())
# # 手动实现Min-Max归一化
# def min_max_normalize(df):
#     df_normalized = (df.iloc[:,1:] - df.iloc[:,1:].min()) / (df.iloc[:,1:].max() - df.iloc[:,1:].min())
#     return df_normalized

# df_normalized = min_max_normalize(df)
# print(df_normalized)

原始DataFrame:
   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
A      1
B     10
C    100
dtype: int64
          B         C
0  0.000000  0.000000
1  0.333333  0.333333
2  0.666667  0.666667
3  1.000000  1.000000


In [7]:
import numpy as np
import pandas as pd

data = pd.read_csv('data_set/anneal.data',header=None)
data.columns = [i for i in range(0,data.shape[1]-1)] + ['target']
for i in range(0,data.shape[1]):
    unique = np.unique(data.iloc[:,i].values,return_counts=False)
    print(unique)
# print(data.head)

['?' 'TN' 'ZS']
['C']
['?' 'A' 'K' 'M' 'R' 'S' 'V' 'W']
[ 0  3  4  6  8 10 45 55 65 70]
[ 0 45 50 60 70 80 85]
['?' 'T']
['?' 'A' 'S']
['1' '2' '3' '5' '?']
[  0 300 310 350 400 500 600 700]
['?' 'N']
['?' 'P']
['?' 'D' 'E' 'F' 'G']
['1' '2' '?']
['?' 'Y']
['?' 'Y']
['?' 'Y']
['?' 'B' 'M']
['?' 'Y']
['?']
['?' 'C']
['?' 'P']
['?' 'Y']
['?']
['?' 'Y']
['?' 'Y']
['?']
['?' 'B' 'C' 'V']
['?' 'Y']
['?']
['?']
['?']
['COIL' 'SHEET']
[0.25  0.3   0.301 0.321 0.4   0.451 0.5   0.501 0.599 0.6   0.601 0.651
 0.699 0.7   0.75  0.799 0.8   0.801 0.9   0.901 0.999 1.    1.001 1.09
 1.1   1.2   1.201 1.299 1.3   1.399 1.4   1.5   1.599 1.6   1.601 1.9
 2.    2.2   2.3   2.5   2.501 2.8   2.801 3.    3.2   3.201 3.3   3.5
 4.   ]
[   0.    20.    25.    28.    29.    50.    58.    60.    65.1   75.
  150.   152.   190.   200.1  249.9  250.   255.   255.1  300.1  335.
  355.   356.   356.1  374.9  375.   385.1  450.   500.   515.   519.
  519.9  520.   595.   599.9  600.   600.1  606.9  609.   609.9

In [16]:
from scipy.spatial.distance import hamming
a = np.array(['A','B','C'])
b = np.array([1,3,3])
print(hamming(a,b))

1.0


In [ ]:
X = np.array([
    [0, 1, 1, 2, 0, 3],
    [1, 0, 0, 1, 1, 2],
    [0, 0, 1, 1, 0, 1],
    [1, 1, 0, 3, 1, 4]
])
y = np.array([0, 1, 0, 1])

In [17]:
for i in range(1,37,3):
    print(i)

1
4
7
10
13
16
19
22
25
28
31
34
