In [11]:
from scipy.optimize import minimize
from scipy.io import loadmat
import numpy as np
import pandas
from sklearn.metrics import classification_report

In [2]:
path = 'ex3data1.mat'
data = loadmat(path)
X = np.array(data['X'])
Y = np.array(data['y'])
Y = Y.reshape(-1)
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
X = np.insert(X,0,np.ones(X.shape[0]),axis=1)
w = np.zeros(X.shape[1])
w = np.array(w)

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
def cost(w,X,Y):
    first = np.multiply(Y,np.log(sigmoid(X.dot(w.T))))
    second = np.multiply((1 - Y),np.log(1 - sigmoid(X.dot(w.T))))
    return -np.mean(first+second)

In [6]:
def regularized_cost(w,X,Y,L):
    reg = L / len(X) / 2 * (w[1:]**2).sum()
    return cost(w,X,Y) + reg

In [7]:
def gradient(w,X,Y,L):
    return X.T @ (sigmoid(X.dot(w.T))-Y) / len(X) + w * L / len(X)

In [8]:
w_all = list()
w_else = list()
for i in range(1,11):
    y = Y.copy()
    x = X.copy()
    for j in range(len(y)):
        if y[j] == i:
            y[j] = 1
        else:
            y[j] = 0
    result = minimize(fun=regularized_cost,x0=np.array(w),args=(x,np.array(y),1),method='TNC',jac=gradient,options={'disp':True})
    w_all.append(result.x.tolist())
    w_else.append(result.fun)
print(w_else)

[0.027087680896319043, 0.06858836460413528, 0.07203253150130491, 0.0521139990812578, 0.07685853803109918, 0.03497460508874542, 0.04678922341384134, 0.09354517749954862, 0.08957542598597959, 0.020791608767993793]


In [9]:
w_all = np.array(w_all)
t = sigmoid(X.dot(w_all.T))
out = np.argmax(t,axis=1) + 1
print(out)

[10 10 10 ...  9  9  7]


In [10]:
cnt=0
for i in range(len(out)):
    if out[i]==Y[i]:
        cnt+=1
print(cnt/len(Y))

0.944


In [12]:
print(classification_report(Y,out))

              precision    recall  f1-score   support

           1       0.96      0.98      0.97       500
           2       0.94      0.92      0.93       500
           3       0.94      0.91      0.92       500
           4       0.95      0.96      0.95       500
           5       0.92      0.91      0.92       500
           6       0.97      0.98      0.97       500
           7       0.95      0.95      0.95       500
           8       0.92      0.93      0.92       500
           9       0.92      0.92      0.92       500
          10       0.97      0.99      0.98       500

    accuracy                           0.94      5000
   macro avg       0.94      0.94      0.94      5000
weighted avg       0.94      0.94      0.94      5000

